jobs:
  include:
    - stage: warm_cache
      script:
        - echo "foo" > A.txt
      workspaces:
        create:
          name: workspace2
          paths:
            - foo.txt
    - stage: use_cache
      workspaces:
        use: workspace2
      script:
        - cat A.txt || true
